# javadoc-cleanup: Github action for tidying up javadocs
# 
# Copyright (c) 2020-2021 Vincent A Cicirello
# https://www.cicirello.org/
#
# MIT License
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# 

name: 'javadoc-cleanup'
description: 'Github action for tidying up javadocs'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  path-to-root:  
    description: 'The path to the root of the website'
    required: false
    default: '.'
  base-url-path:
    description: 'The url of your webpage'
    required: false
    default: ''
  user-defined-block:
    description: 'This block will be inserted verbatim into the head of each javadoc page'
    required: false
    default: ''
outputs:
  modified-count:
    description: 'The number of html files modified by javadoc-cleanup.' 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path-to-root }}
    - ${{ inputs.base-url-path }}
    - ${{ inputs.user-defined-block }}
