name: build

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Python unit tests
      run: python3 -u -m unittest tests/tests.py

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag javadoc-cleanup:$(date +%s)
